networks:
  Red interconectada: {}
  crane-net: {}
  prometheus-net:
    external: true
services:
  Service2:
    environment:
      nose: nose
    image: node
    labels:
    - a.label.name=nombredeappp-4
    - traefik.http.routers.nombredeappp-4-Service2.rule=Host(`nombredeappp-4-Service2.docker.localhost`)
    networks:
    - Red interconectada
    - crane-net
    ports:
    - '3000'
    restart: unless-stopped
    volumes:
    - /:/app
  servicio:
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_PASSWORD: userpass
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: user
    image: mysql
    labels:
    - hola
    - a.label.name=nombredeappp-4
    - traefik.http.routers.nombredeappp-4-servicio.rule=Host(`nombredeappp-4-servicio.docker.localhost`)
    networks:
    - Red interconectada
    - crane-net
    ports:
    - '3306'
    restart: unless-stopped
    volumes:
    - /:/var/lib/mysql
  traefik-proxy:
    command:
    - --api.insecure=true
    - --providers.docker=true
    - --accesslog=true
    - --accesslog.format=json
    - --metrics.prometheus=true
    - --metrics.prometheus.buckets=0.1,0.3,1.2,5.0
    - --entrypoints.web.address=:80
    - --providers.docker.constraints=Label(`a.label.name`, `nombredeappp-4`)
    - --providers.docker.watch=true
    image: traefik:latest
    networks:
    - crane-net
    - prometheus-net
    ports:
    - 0:80
    - 0:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
