networks:
  crane-net: {}
  name: {}
  prometheus-net:
    external: true
services:
  Service 1:
    command: null
    environment:
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_USERNAME: root
    image: mongo
    labels:
    - ANACHE
    - asdnaisod
    - a.label.name=rplqopwrq
    - traefik.http.routers.rplqopwrq.rule=Host(`rplqopwrq-Service 1.docker.localhost`)
    networks:
    - name: Network 1
    ports:
    - '27017'
    resources:
      limits:
        cpus: null
        memory: null
    restart_policy: unless-stopped
    startup_scripts: []
    volumes:
    - path: /:/ELMATIU
      size: 20
  traefik-proxy:
    command:
    - --api.insecure=true
    - --providers.docker=true
    - --accesslog=true
    - --accesslog.format=json
    - --metrics.prometheus=true
    - --metrics.prometheus.buckets=0.1,0.3,1.2,5.0
    - --entrypoints.web.address=:80
    - --providers.docker.constraints=Label(`a.label.name`, `rplqopwrq`)
    - --providers.docker.watch=true
    image: traefik:latest
    networks:
    - crane-net
    - prometheus-net
    ports:
    - 0:80
    - 0:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
